DataDog/dd-apm-test-agent

- releasenotes/notes/python-support-1c447acc4607abc7.yaml
- setup.py
> Fix required Python version

- LICENSE.BSD3
- setup.py
> Fix BSD license, setup.py

- README.md
- ddapm_test_agent/agent.py
- releasenotes/notes/session-requests-b8057811f976220e.yaml
- tests/test_session.py
Add endpoint to return all requests made in a session.
> Add session requests endpoint

- README.md
- ddapm_test_agent/agent.py
- ddapm_test_agent/tracestats.py
- releasenotes/notes/trace-stats-97da3a478dabfa99.yaml
- setup.py
- tests/conftest.py
- tests/test_session.py
- tests/test_stats.py
Note that support for snapshotting will be included in a follow-up
patch.
Dependent on #50
> Add support for /v0.6/stats

- tests/test_snapshot_integration.py
ddtrace has deprecated explicit usage of the writer
> Upgrade ddtrace usage

- README.md
- ddapm_test_agent/agent.py
- ddapm_test_agent/tracestats_snapshot.py
- releasenotes/notes/trace-stats-snapshot-718ca37385c93e1e.yaml
- tests/integration_snapshots/test_trace_stats_tracestats.json
- tests/test_snapshot.py
- tests/test_snapshot_integration.py
Implement trace stats snapshotting so that trace stats are included in
snapshots.
> Add trace stats snapshot functionality

- ddapm_test_agent/agent.py
- releasenotes/notes/info-drop-p0s-c207889f590340fb.yaml
- tests/test_agent.py
This feature goes with the /v0.6/stats (trace stats) implementation.
> Add ClientDropP0s feature to info endpoint

- ddapm_test_agent/agent.py
- releasenotes/notes/profiling-endpoint-0cd209e4e5b6cfc0.yaml
- tests/test_snapshot_integration.py
Just handle the request, nothing else.
> Add support for profiling

- .github/workflows/main.yml
- ddapm_test_agent/agent.py
- ddapm_test_agent/trace_checks.py
mypy released a new version which removed the need for some of the  type ignores.
> Fix typing

- README.md
https://github.com/badges/shields/issues/8671
> Fix readme branch checks badge

- Dockerfile
- releasenotes/notes/python310-docker-image-d4e329cfecf6510e.yaml
This should yield some performance benefit and more importantly, better error messages to assist with debugging.
> Update docker image to use Python 3.11

- .github/workflows/publish_pypi.yml
- README.md
- ddapm_test_agent/agent.py
- ddapm_test_agent/remoteconfig.py
- releasenotes/notes/add-session-to-rcm-endpoints-d97e925a04a99a65.yaml
- tests/test_remoteconfig.py
Add session token to Remote Config endpoint.
> feat(rcm): add session token to endpoints

- README.md
- ddapm_test_agent/agent.py
- ddapm_test_agent/checks.py
- ddapm_test_agent/trace_checks.py
- releasenotes/notes/Checks-changed-to-opt-in-8716cac4ecdbb1c2.yaml
- tests/conftest.py
- tests/test_checks.py
Merge conflict until #133 is merged
> Make checks opt-in

- README.md
- ddapm_test_agent/agent.py
- ddapm_test_agent/checks.py
- releasenotes/notes/improve-trace-check-results-endpoints-6ab4132628520793.yaml
- tests/conftest.py
- tests/test_agent.py
PR adds improvements to the `tests/trace check/results` endpoint. It breaks down the number of checks run by type of trace check, adds the ability to clear Trace Check results, and can return results for the number of passed, failed, and skipped checks.
> feat: improve trace check results endpoint

- README.md
Fix intra-document anchor links
> Fix anchor links within document

- ddapm_test_agent/trace.py
- ddapm_test_agent/trace_snapshot.py
- releasenotes/notes/span-links-1ec76bd2b47a3880.yaml
- tests/test_snapshot.py
Allow parsing, validating and returning span links.
This is a pre-requisite for proper system-tests.
> Add span link support

- .github/workflows/main.yml
- README.md
- ddapm_test_agent/agent.py
- ddapm_test_agent/checks.py
- ddapm_test_agent/remoteconfig.py
- ddapm_test_agent/trace_checks.py
- ddapm_test_agent/tracerflare.py
- riotfile.py
- test_deps.txt
- tests/test_snapshot_integration.py
Looks like a few things were exposed with more recent mypy releases.
> Fix various types

- .github/workflows/main.yml
- Dockerfile
- releasenotes/notes/python-3.12-952e06c6158af67d.yaml
- riotfile.py
- setup.py
- tests/conftest.py
Also only test the oldest and newest versions supported.
> Add Python 3.12 support

- Dockerfile
It's also kind of nice to be able to query the test agent from within its own container
> Add curl back into the container for .NET

- .github/workflows/main.yml
> Bump action versions

- setup.cfg
- setup.py
Adds ddsketch[serialization] as dependency as we need the protobuf dependency too.
> add ddsketch[serialization] as dependency

- ddapm_test_agent/trace.py
This PR fix a stutter left after refactoring the meta_struct implementation done in #184
> fix: wrong meta_struct verification

- .github/workflows/docker.yml
[](https://datadoghq.atlassian.net/browse/VULN-8095)
> Explicitly state write permissions on publish job

- .github/workflows/publish_pypi.yml
The download-artifact job has been discontinued
> Fix pypi publish

- ddapm_test_agent/agent.py
- tests/test_agent.py
[](https://datadoghq.atlassian.net/browse/MLOB-1832)
> Record and return LLMObs proxied requests

- ddapm_test_agent/agent.py
- ddapm_test_agent/trace_snapshot.py
- releasenotes/notes/SNAPSHOT_REGEX_PLACEHOLDERS-compare-c829e7a4df4fa1f4.yaml
Yep, the generation step worked fine. Tested it and got the expected json dumps. Then compared it and it did not match anything. Fix the missing step.
> Also apply the regex replaces during the comparison step

- ddapm_test_agent/agent.py
- releasenotes/notes/llmobs-eval-metric-endpoint-8b5222491969ab4f.yaml
- tests/test_agent.py
adds our llm observability evaluation metrics endpoints to the trace agent
> Add LLM Observability evaluation metrics endpoints

- releasenotes/notes/more-oai-cass-908eb5ea46bd2985.yaml
- vcr-cassettes/openai/openai_chat_completions_post_3517e44e.yaml
- vcr-cassettes/openai/openai_chat_completions_post_36bdc0cb.yaml
- vcr-cassettes/openai/openai_responses_post_33fb1f66.yaml
- vcr-cassettes/openai/openai_responses_post_5ca556ec.yaml
- vcr-cassettes/openai/openai_responses_post_c05c936e.yaml
- vcr-cassettes/openai/openai_responses_post_c61e3067.yaml
Add OpenAI vcr cassettes for responses api prompt caching, responses api streaming prompt caching, and chat completions with tool calls.
> chore(llmobs): more openai cassettes

- .github/workflows/docker.yml
- Dockerfile
- Dockerfile.windows
- ddapm_test_agent/tracestats.py
- releasenotes/notes/Use-default-value-for-null-fields-in-tracestats-55d465f489efb2ba.yaml
- releasenotes/notes/windows-docker-image-1f5d5e894558bb4b.yaml
- setup.py
- test_deps.txt
- tests/integration_snapshots/test_trace_stats_tracestats.json
Adds Windows image artifact and publishing to the build process.
> feat: python 3.13 + windows image
