DataDog/dd-apm-test-agent

.github/workflows/main.yml
CI would previously not run on PRs from forked repositories.
=> Run CI on pull request as well

ddapm_test_agent/agent.py, ddapm_test_agent/snapshot.py, releasenotes/notes/fix-matching-319744b82d2514c1.yaml, tests/test_snapshot_integration.py
The previous matching algorithm assumed that trace ids would be unique
across both sets of traces which is not true for snapshots as the traces
are normalized.
Fixes #25
=> Fix matching algorithm

ddapm_test_agent/agent.py, ddapm_test_agent/snapshot.py, releasenotes/notes/reuse-session-1670aa569907cf68.yaml, tests/integration_snapshots/test_trace_missing_received.json, tests/test_session.py, tests/test_snapshot_integration.py
The API for retrieving traces from the session would return all traces
matching the session token and not just the most recent traces for the
session.
Actually fixes #25
=> Fix multiple sessions

README.md, ddapm_test_agent/snapshot.py, releasenotes/notes/snapshot-empty-maps-2cbe8cea3e7112fa.yaml, tests/integration_snapshots/test_multi_trace.json, tests/integration_snapshots/test_single_trace.json, tests/integration_snapshots/test_trace_distributed_same_payload.json, tests/integration_snapshots/test_trace_missing_received.json, tests/test_snapshot.py
This should help make snapshots more concise.
=> Don't include empty meta/metrics in snapshots

README.md, ddapm_test_agent/fmt.py, releasenotes/notes/add-fmt-command-cc31769942a5fec3.yaml, setup.py
New command that can be used to reformat snapshot
files to ensure a consistent style.
You can also use the command to check/error if files
are not conforming to the expected format.
```
$ ddapm-test-agent-fmt -h
usage: ddapm-test-agent-fmt [-h] [-v] [-c] [--log-level LOG_LEVEL] FILE [FILE ...]
Datadog APM Test Agent Snapshot Formatter
positional arguments:
FILE                  Specific snapshot files or directories to format.
optional arguments:
-h, --help            show this help message and exit
-v, --version         Print version info and exit.
-c, --check           Do not rewrite files, error if any files would be changed.
--log-level LOG_LEVEL
Set the log level. DEBUG, INFO, WARNING, ERROR, CRITICAL.
```
=> feat: Add ddapm-test-agent-fmt command

.github/workflows/main.yml, README.md, riotfile.py, setup.py, test_deps.txt, tests/integration_snapshots/test_multi_trace.json, tests/integration_snapshots/test_single_trace.json, tests/integration_snapshots/test_trace_distributed_same_payload.json, tests/integration_snapshots/test_trace_missing_received.json
This enables dependencies to be shared between manual installing `pip install -e .[testing]` and testing and riot.
The snapshots are updated since there have been some `ddtrace` changes.
=> Move testing dependencies to file

README.md, ddapm_test_agent/agent.py, releasenotes/notes/snapshot-filename-c068de1bc3e50c04.yaml, tests/test_snapshot.py
The filename before had to include the extension which wasn't intended.
=> Fix custom snapshot filename

ddapm_test_agent/fmt.py
The command was failing for snapshot directories containing both trace
and trace stats snapshots because it assumes that all json files are
trace snapshots.
Just ignore the trace stats snapshots for now.
=> Ignore trace stats file in fmt command

ddapm_test_agent/trace.py, releasenotes/notes/span-parent-id-a4d7d63fa623361c.yaml, setup.py, tests/test_trace.py
Use the new [`TypedDict`](https://peps.python.org/pep-0655/) implementation that supports `NotRequired` and `Required` to better type the data that the agent can receive from clients.
Fixes #65.
=> Handle span parent_id being undefined

ddapm_test_agent/trace_snapshot.py, releasenotes/notes/snapshot-error-messages-de41d9e3207fa30a.yaml, tests/test_snapshot.py
Be more verbose about received/expected traces rather than just spitting
out a normalized trace id.
=> Generate better snapshot error messages

ddapm_test_agent/trace_snapshot.py, releasenotes/notes/snapshot-parent-id-7abb860008702e70.yaml, tests/test_snapshot.py
Fixes a "missing `parent_id`" issue in the snapshot generation.
https://github.com/DataDog/dd-apm-test-agent/pull/66 fixed the issue when receiving traces, this fixes the issue when generating snapshots.
Caveats: this is about the first Python I've written 😉 
Fixes #65.
=> Handle span `parent_id` being undefined in snapshots

README.md, tests/test_snapshot_integration.py
Previously, in order to generate snapshots the pytest fixture had to be
parametrized to be set to false. This was a bit clunky and not at all
intuitive for new developers.
Now a flag, `GENERATE_SNAPSHOTS=1` can be passed when running the
integration tests which will enable the snapshots to be output.
=> Add testing flag for snapshot generation

riotfile.py, tests/integration_snapshots/test_trace_stats_tracestats.json, tests/test_snapshot_integration.py
This was added by commented out since trace stats support had not yet
been added to the python client library.
Pulls most of the unrelated work out of #76
=> Enable tracestats integration test

README.md, ddapm_test_agent/trace.py, ddapm_test_agent/trace_snapshot.py, releasenotes/notes/add-distributed-trace-c35a314698a3b966.yaml, setup.py, tests/integration_snapshots/test_trace_distributed_propagated.json, tests/test_snapshot_integration.py, tests/test_trace.py, tests/trace_utils.py
Add support for distributed traces where an instrumented service sends a trace chunk where the root span has a parent not in the trace chunk.
=> feat: add support for distributed traces

README.md, ddapm_test_agent/agent.py, releasenotes/notes/uds-64b11960931d8b77.yaml
```
(.venv) ~/d/dd-apm-test-agent ❮❮❮ ddapm-test-agent --uds-path=./apm.socket
======== Running on http://0.0.0.0:8126, http://unix:/Users/kverhoog/dev/dd-apm-test-agent/apm.socket: ========
(Press CTRL+C to quit)
```
Resolves #67
=> Add support for UDS

ddapm_test_agent/agent.py, ddapm_test_agent/trace_checks.py, releasenotes/notes/content_length-e1bab75580aa1dcb.yaml, tests/conftest.py
The check assumed that the header would always be included. Some
clients, particularly the go client, don't include this header.
=> Fix trace_content_length check

ddapm_test_agent/agent.py, releasenotes/notes/info-34dcd9cbcc382487.yaml, tests/test_agent.py
The info endpoint exists to allow clients to detect what features are
available in the agent. The go tracer specifically will only enable
trace stats computation if it detects that the agent supports the
feature.
=> Add /info endpoint support

ddapm_test_agent/tracestats.py, releasenotes/notes/tracestats-service-2a0a178cbd21b07d.yaml, tests/conftest.py
=> Decode service in trace stats payloads

ddapm_test_agent/agent.py, ddapm_test_agent/checks.py, ddapm_test_agent/trace_checks.py, releasenotes/notes/throttling-590bf58ecb3cc4a5.yaml, tests/conftest.py, tests/test_checks.py
Introduce a new feature that allows the artificial throttling of the test agent for specific (or all) requests to mimic a real agent being under load.
=> Add stall feature for trace requests

ddapm_test_agent/agent.py, releasenotes/notes/traces-endpoint-f4f9c1d94d6ceda2.yaml
The /test/traces endpoint was using all gathered requests, assuming that
they were trace requests. This cause the endpoint to fail if telemetry
or stats requests are sent.
It was noticed that support for v0.5 wasn't present either so that is fixed too.
Thanks @bengl for finding this the hard way.
=> Only process trace requests with /test/traces endpoint

riotfile.py
It broke with the latest flake8 release: https://github.com/globality-corp/flake8-logging-format/issues/35
=> Disable flake8-logging-format plugin

tests/integration_snapshots/test_multi_trace.json, tests/integration_snapshots/test_single_trace.json, tests/integration_snapshots/test_trace_distributed_same_payload.json, tests/integration_snapshots/test_trace_missing_received.json
The 1.3 release of ddtrace introduced a new tag which breaks the snapshot integration tests.
=> Update snapshot integration tests for ddtrace 1.3

ddapm_test_agent/agent.py, releasenotes/notes/uds-permissions-903266ac6445b873.yaml
The permissions of the socket created by aiohttp aren't as permissive as
the ones set by the real agent. (see
https://github.com/aio-libs/aiohttp/issues/4155)
from @devinsba:
test agent:
```
cnb@my-app:/var/run/datadog$ ls -la
total 4
drwxr-xr-x 2 root root   60 Aug  1 21:24 .
drwxr-xr-x 1 root root 4096 Aug  1 21:24 ..
srwxr-xr-x 1 root root    0 Aug  1 21:24 apm.socket
```
real agent:
```
cnb@my-app:/var/run/datadog$ ls -la
total 4
drwxr-xr-x 2 root root   80 Aug  1 21:30 .
drwxr-xr-x 1 root root 4096 Aug  1 21:31 ..
srwx-w--w- 1 root root    0 Aug  1 21:30 apm.socket
```
aiohttp doesn't seem to have a configurable way
to set these permissions but it does let us create and
manage a socket ourselves, so let's try that.
=> Set 722 file permissions on UDS socket

ddapm_test_agent/cmd.py, releasenotes/notes/snapshot-cmds-de4a561911afee11.yaml, riotfile.py, setup.py, tests/test_snapshot_integration.py
Add commands to start and perform snapshot test cases to ease
manual/CI usage. The alternative would be to curl and try to parse the
results which isn't trivial to do.
=> Add snapshot commands

README.md, ddapm_test_agent/trace_snapshot.py, releasenotes/notes/new-process-id-tag-f0ab0daf652e05cc.yaml
This tag is replacing the system.pid tag.
=> Add `metrics.system.process_id` to ignored tags

ddapm_test_agent/agent.py, releasenotes/notes/fix-racecondition-9bd0ef15b7da60fa.yaml, tests/conftest.py, tests/test_snapshot_integration.py
As discovered in https://github.com/DataDog/system-tests/pull/607, concurrent requests to the test agent that read and write the data (like sending and retrieving traces) could result in:
```
File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 184, in _traces_from_request
return await self._decode_v04_traces(req)
File "/usr/local/lib/python3.9/site-packages/ddapm_test_agent/agent.py", line 238, in _decode_v04_traces
raw_data = await request.read()
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_request.py", line 649, in read
chunk = await self._payload.readany()
File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 397, in readany
await self._wait("readany")
File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 295, in …
```
=> Fix race condition for simultaneous reading and writing

docker-compose.yml
It is not used and doesn't need to be used for local development.
=> Remove docker-compose file

ddapm_test_agent/agent.py, ddapm_test_agent/trace_checks.py, releasenotes/notes/check-http-header-sensitivity-daaa9d9595ae86d6.yaml, tests/test_checks.py
The headers were pointlessly being cast to a normal dictionary from a case insensitive multi dict implementation.
Fixes #112
=> Fix case sensitive headers

.github/workflows/publish_pypi.yml
Update deprecate CI image
CI [Build wheels](https://github.com/DataDog/dd-apm-test-agent/actions/runs/4729624217/jobs/8392342342?pr=76#logs) step tries to use `ubuntu-18.04` image but It's deprecated and the job stucks:
```
Requested labels: ubuntu-18.04
Job defined at: DataDog/dd-apm-test-agent/.github/workflows/publish_pypi.yml@refs/pull/76/merge
Waiting for a runner to pick up this job...
Job is cancelled before starting.
```
=> fix(ci): build wheels step image

ddapm_test_agent/agent.py, ddapm_test_agent/trace.py, releasenotes/notes/improve-test-agent-debugging-5759413f1fc5f7fa.yaml
This change adds more informative debug and error message to the test agent when handling traces. New debug messages include the raw request being handled and the request headers. Additionally, when verifying a decoded trace, Assertion errors have been updated to include a message of actual vs expected keys/values/types.
=> feat: add more informative debug and error messages to test-agent

README.md, ddapm_test_agent/agent.py, ddapm_test_agent/trace.py, ddapm_test_agent/trace_snapshot.py, releasenotes/notes/allow-attribute-removal-snapshots-314b744b043b97c5.yaml, tests/conftest.py, tests/test_snapshot.py, tests/trace_utils.py
Add a new _optional_ configuration to allow fields to be removed from the spans. By default, no keys will be removed from the snapshots.
💭 The motivation behind this feature is to get rid of some fields that can be noisy in the snapshots (e.g., `start` or `duration`) which could create some massive diffs when regenerating the snapshots.
Note that since the removal of the field `start` would cause an error when sorting the spans by this field, `span_id` was used as a fallback. Feel free to tell me if this would cause an issue I didn't consider (this is the reason why both `start` and `span_id` shouldn't be removed from the snapshots).
=> Add `SNAPSHOT_REMOVED_ATTRS` to remove attributes from spans in snapshots

ddapm_test_agent/agent.py, releasenotes/notes/add-request-forwarding-middleware-d3f325166b0f8e9e.yaml
This PR adds two middlewares to the Test-Agent. The first middleware stores the request data and headers in Test-Agent memory. The second middleware forwards requests to an optional end destination (such as a real DD Agent) for any requests from the `/traces`, `/stats`, or `/telemetry` endpoints.
=> add request forwarding for telemetry

README.md, ddapm_test_agent/agent.py, releasenotes/notes/pipeline_stats_endpoint-e8ad6da735dc2647.yaml
Add pipeline stats endpoint to the test agent.
For now, I'm not storing anything, the goal here is just to avoid errors when trying to submit payloads to the test agent.
=> Add pipeline stats endpoint

ddapm_test_agent/agent.py, ddapm_test_agent/checks.py, releasenotes/notes/additional-checks-3e25e1d310b1de4a.yaml, tests/conftest.py
Adds a config to allow some languages to use checks that are not enabled by default. Unblocks #127
=> Add flag for enabling non-default checks

ddapm_test_agent/agent.py, ddapm_test_agent/checks.py, releasenotes/notes/additional-checks-3e25e1d310b1de4a.yaml, tests/conftest.py
Reverts DataDog/dd-apm-test-agent#131
We have decided to instead require listing the checks that are being used
=> Revert "Add flag for enabling non-default checks"

ddapm_test_agent/agent.py, releasenotes/notes/add-support-for-plain-text-responses-00d20bf7b335e75b.yaml
new content type, necessary for Ruby service naming tests
=> add plain text content type

ddapm_test_agent/agent.py, releasenotes/notes/fix-getting-tested-integrations-multiple-session-tokens-4ee41d545754f87f.yaml
Currently, the test agent will only return tested integrations for a specific token, and there is no way to get all tested integrations if multiple tokens were used. This PR changes that to allow for getting all tested integrations if no session token is included.
=> Get all integration requests if session token is none

ddapm_test_agent/trace_snapshot.py, releasenotes/notes/ignore-dsm-pathway-hash-during-trace-snapshots-f0b99ea267fbad48.yaml
Ignore `pathway.hash` to prevent trace snapshot failures
=> chore: ignore DSM pathway hash within trace snapshot

setup.cfg
aiohttp warns about using str keys on the app instance as it can interfere with mypy typing. Right now it spams up the test logs and we don't use it that heavily so ignore the warnings.
More on the warning: https://docs.aiohttp.org/en/stable/web_advanced.html#application-s-config
=> Ignore aiohttp warnings

.github/workflows/main.yml
CI no longer runs on every commit (to avoid duplicate runs on PRs) but now it doesn't run on master. Even though PRs have to be up to date in order to be merged, running on master gives some more signal to help identify flaky tests.
=> Run ci on master

ddapm_test_agent/agent.py, ddapm_test_agent/tracerflare.py, releasenotes/notes/fix-tracerflare-request-parsing-fae18ff9997c216d.yaml
Fixing a few errors in the way tracer flare requests are handled by the test agent.
- The parsing was failing because the MultipartReader was given an instance of asyncio.StreamReader instead of aiohttp.StreamReader
- When a parsing error occurred, it was not returned to the client
=> Fix handling of traceflare requests

ddapm_test_agent/trace.py, tests/test_session.py, tests/test_snapshot_integration.py
This is a quick change which fixes some fmt issues (using riot run -s fmt) and a test output which was hard to debug
=> (chore) refactor: fmt + test output

ddapm_test_agent/trace_snapshot.py, releasenotes/notes/ignore-new-metric-in-snapshots-fca905ba6d687929.yaml
A new metric, metrics._dd.tracer_kr, was added to `dd-trace-py` causing snapshot tests tofail.  This metric is now added to the list of ignored snapshot fields.
=> (fix) tests: Ignore new metric

ddapm_test_agent/agent.py, releasenotes/notes/exception-messages-21ee64461020edd1.yaml
Prior to this change debugging the handle_snapshot function was difficult, because no error message beyond "INTERNAL SERVER ERROR" was returned.  After this change, the exception's message is returned.
=> (chore): add error string to handle_snapshot

ddapm_test_agent/trace_snapshot.py, test_deps.txt, tests/integration_snapshots/test_multi_trace.json, tests/integration_snapshots/test_single_trace.json, tests/integration_snapshots/test_trace_distributed_propagated.json, tests/integration_snapshots/test_trace_distributed_same_payload.json, tests/integration_snapshots/test_trace_missing_received.json, tests/integration_snapshots/test_trace_stats_tracestats.json
It looks like a new tag meta._dd.p.tid was added which should probably be handled by the test agent since I believe it's used for 128-bit trace ID support.
=> Bump ddtrace version to 2.6.0

ddapm_test_agent/agent.py, releasenotes/notes/clearing-sessions-now-only-removes-traces,-instead-of-sessions,-requsting-traces-will-now-return-a-404-error-for-TracesNotFound-if-a-session-is-specified-and-traces-are-not-found-6b0311673d8b37aa.yaml, tests/conftest.py, tests/test_session.py, tests/test_snapshot_integration.py
Does the following:
- Clearing a session now clears traces only, instead of also deleting the session
- Requesting traces for a esssion will return a 404 Session Not found if no traces or session match a non-None session token
- Sessions now return session-less requests only up to the latest session marker
=> (feat): update session logic

Dockerfile, releasenotes/notes/image-optimization-d614eccb59441217.yaml
The current image is >1.2gb and not at all optimized. We can utilize the python-slim base image and remove unnecessary files in the image. With these changes we cut the image size to less than half (500mb on my local machine).
=> Optimize docker image

Dockerfile
This will help speed up testing as the image will largely be cached when non-critical files are touched.
=> Add only necessary files to image

ddapm_test_agent/agent.py, releasenotes/notes/uds-container-8138f8b1438b1a0a.yaml, tests/test_container.py
As far as I can tell there is an issue with binding a socket and `chmod`-ing it on macOS. I have repro'd the issue here:
```
>>> server_socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
>>>
>>> server_socket.bind(socket_path)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'socket_path' is not defined
>>> server_socket.bind("/tmp/run/test.sock")
>>> import os
>>> os.chmod("/tmp/run/test.sock", 0o722)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument: '/tmp/run/test.sock'
```
I think it has something to due with volumes and sockets not playing nicely together on docker for mac.
Anyway, this crashes the test agent on start-up and it's not the end of the world if the permissions don't …
=> Fix container failing to start with UDS

.github/workflows/main.yml, tests/test_container.py
Until we can get https://github.com/DataDog/dd-apm-test-agent/pull/174 merged.
=> Skip macOS containers test in CI

ddapm_test_agent/client.py, releasenotes/notes/client-173dbc6655e42337.yaml, tests/conftest.py, tests/test_client.py, tests/test_snapshot_integration.py
Add a client API so that the testagent can be interfaced with natively in Python. This can be used in projects like system-tests and the injector test suite.
Typing is a best-effort as this is needed ASAP in https://github.com/DataDog/auto_inject/pull/133
=> Add client API

ddapm_test_agent/agent.py, releasenotes/notes/addPeerTagsToInfo-4ccc2539d22c2993.yaml
As part of moving towards enabling client-side-stats by default we want to add some parametric tests. To provide some peer_tags to test with this change starts returning the `peer_tags` as expected by the datadog-agent (PR for that change here: https://github.com/DataDog/datadog-agent/pull/27603 )
=> Add peer_tags to info endpoint

.github/workflows/changelog.yml
This broke somewhere along the way and we weren't using them anyway so easy cleanup.
=> Remove unused changelog steps

ddapm_test_agent/trace.py, releasenotes/notes/meta-struct-2cce08475cb05470.yaml, tests/test_trace.py
This PR adds support for a specific field supported since agent version v7.31 called `meta_struct` which encapsulate another layer of msgpack values inside the main msgpack chunk.
Appsec has been using this field to store stacktraces for multiple quarters already. We need to be able to test this feature
Not overly happy about this implementation but there is not obvious way to do a first round of type checking, modify the span object, and then do a second round of type-checking. So I've simply put everything in the `verify_span` function.
=> feat: meta_struct support

ddapm_test_agent/tracerflare.py
aiohttp itself is ignoring some types which breaks our type-checking (as far as I can tell).
```
def __aiter__(
self,
) -> AsyncIterator["BodyPartReader"]:
return self  # type: ignore[return-value]
```
=> Fix typing on asyncio `MultipartReader` usage

.github/workflows/releasenote.yml, releasenotes/check-releasenotes
All other references are release note so let's keep it consistent to avoid confusion.
=> Rename changelog references to release notes

setup.py
These files were included in the wheel but are unnecessary for the library to function. This indirectly fixes #188 since a releasenote file name is too long for Windows.
=> Remove unnecessary files from Python package

.github/workflows/docker.yml, .github/workflows/publish_pypi.yml, .github/workflows/releasenote.yml
We were relying on deprecated GH actions that are causing pipeline failures, this PR moves us to the latest version of these.
=> Move to non-deprecated github actions

ddapm_test_agent/agent.py, releasenotes/notes/addAgentStateToInfo-f9a179ce88f2ab9e.yaml
Add a dummy value for the `Datadog-Agent-State` header
=> Add agent state header to info endpoint

README.md, ddapm_test_agent/agent.py, ddapm_test_agent/apmtelemetry.py, releasenotes/notes/Settings-endpoint-928ae5b6e8ddc625.yaml, releasenotes/notes/Telemetry-requests-delay-2586180b286ce393.yaml, tests/test_agent.py
Extend `--trace-request-delay` to also affect trace requests.
Also, add a `test/settings` endpoint to change the value of settings on the fly.
=> Add delay for telemetry requests

.dockerignore, .envrc.example, .github/workflows/nix-auto.yml, .gitignore, README.md, build-on-darwin.Dockerfile, ddsketch.nix, ddtrace.nix, flake.lock, flake.nix, releasenotes/notes/add-nix-build-support-29dc8a347e3bd7c1.yaml, shell.nix, tests/integration_snapshots/test_trace_distributed_propagated.json, tests/test_agent.py, tests/test_container.py, tests/test_snapshot_integration.py, treefmt.nix, use-example.Dockerfile
Add ability to configure, compile and run the test agent using only nix.
=> Build using nix 

ddapm_test_agent/agent.py
Returning is deprecated apparently.
Fixes #171
=> Raise HTTPExceptions rather than returning

.github/workflows/publish_pypi.yml, releasenotes/notes/wheels-68a7dc2f4b00e0c4.yaml
We were building them, just not uploading to PyPI.
Fixes #206
=> Publish wheels to PyPI

ddapm_test_agent/agent.py, releasenotes/notes/evp-proxy-on-info-d65cd077575306ca.yaml, tests/test_agent.py
Some tracers rely on the existence of `/evp_proxy/v2` for evp proxy feature discovery. This PR adds it so those tracers can properly set up EVP proxy.
=> fix: add evp_proxy endpoint to /info agent endpoint

ddapm_test_agent/vcr_proxy.py, releasenotes/notes/vcr-support-querystring-b06555fb9a7c90ae.yaml
Currently URLs containing query strings will be hashed to the same cassette. This isn't ideal for cases where arguments are passed via the query string as the returned cassette will be constant.
Solution is to simply factor in the query string into the hash.
=> Add support for query strings to VCR

README.md
Fix the example for the `/test/session/responses/config (POST)` that was using another endpoint in the README.
=> fix(readme): fix example of the responses config endpoint

ddapm_test_agent/vcr_proxy.py, releasenotes/notes/vcr-proxy-use-test-name-bugfix-be758294ba30ac78.yaml
instead, we pop the name from the request dict-like object, so that cassette name generation works properly. i _think_ this is only true when there is no suffix being used (ie value of `None`), which is still a valid use case.
example:
```bash
File "/usr/local/lib/python3.12/site-packages/google/genai/errors.py", line 105, in raise_for_response
raise ClientError(status_code, response_json, response)
google.genai.errors.ClientError: 400 'vcr_cassette_suffix'. {'message': "400: 'vcr_cassette_suffix'", 'status': "'vcr_cassette_suffix'"}
```
Additionally, make sure Google GenAI API keys are omitted from cassettes
=> fix(vcr): attaching vcr suffix name to the request results in 400s from providers, omit google api key from cassettes

ddapm_test_agent/agent.py, ddapm_test_agent/vcr_proxy.py, releasenotes/notes/vcr-prefix-instead-of-suffix-4c56dcb5038d222e.yaml
Cassette name additions passed in as `test_name` for `/vcr/test/start` are now used as a prefix for generated cassette names instead of a suffix.
`openai_embeddings_post_48694087_test_embedding.yaml` &rarr; `test_embedding_openai_embeddings_post_48694087.yaml`
tested by using this dev image in some shared test tooling for datadog llm observability
=> upgrade(vcr): use test name for vcr cassettes as a prefix rather than a suffix

README.md, ddapm_test_agent/__init__.py, ddapm_test_agent/agent.py, ddapm_test_agent/client.py, ddapm_test_agent/logs.py, flake.nix, releasenotes/notes/otlp-logs-support-d5a150d9f5304d7c.yaml, setup.py, tests/test_agent.py, tests/test_logs.py
The dd-apm-test-agent currently supports testing APM traces and metrics but lacks support for OpenTelemetry logs. As OpenTelemetry adoption grows, there's a need to test OTLP logs exporters and libraries that send logs in the standard OTLP v1.7.0 protobuf format. This gap makes it difficult to validate OpenTelemetry logs instrumentation and exporter behavior in testing environments.
This PR adds OTLP logs support to the dd-apm-test-agent by implementing a dual-server architecture that maintains separation between APM and OTLP endpoints while sharing session management.
Key Changes:
- New OTLP HTTP Server: Dedicated server on port 4318 with /v1/logs endpoint that accepts OTLP protobuf payloads
- Shared Agent Instance: Both APM (port 8126) and OTLP (port 4318) servers use the same Agent …
=> otel: Add OTLP logs support via HTTP endpoint

ddapm_test_agent/agent.py, tests/test_agent.py
Fix Unix socket handling in ddapm-test-agent. Fixes regression introduced in https://github.com/DataDog/dd-apm-test-agent/commit/88600bb80afabc423c1f3d14f0a8146357cab8b7.
- **Main Fix**: Ensure `UnixSite(...,...)` is called with socketname and not the socket object. 
- Fixed Unix socket permissions: Set socket permissions after aiohttp server startup to ensure correct 0o722 permissions
- Fixed test permissions check: Use stat.S_IMODE() to properly extract permission bits from socket file mode
=> agent: fix unix site and test permissions

README.md, ddapm_test_agent/agent.py, ddapm_test_agent/client.py, ddapm_test_agent/logs.py, ddapm_test_agent/metrics.py, releasenotes/notes/add-otel-metrics-support-a2ebeb28cae2f0ba.yaml, tests/conftest.py, tests/test_logs.py, tests/test_metrics.py
This PR adds comprehensive OpenTelemetry Protocol (OTLP) metrics support to the test agent, extending the existing OTLP logs functionality to also handle metrics payloads on both HTTP and GRPC protocols.
New Functionality:
Added /v1/metrics HTTP endpoint accepting OTLP metrics in protobuf and JSON formats
Implemented GRPC MetricsService.Export method with forwarding to HTTP backend
Added /test/session/metrics endpoint for retrieving captured metrics per session
Extended OTLP test client with metrics() and wait_for_num_metrics() methods
Core Implementation:
ddapm_test_agent/metrics.py: New module with decode_metrics_request() function and OTLPMetricsGRPCServicer class following the same patterns as the logs module
ddapm_test_agent/agent.py: Added metrics handling methods …
=> feat: OTLP Metrics Support

README.md, ddapm_test_agent/agent.py, ddapm_test_agent/vcr_proxy.py, releasenotes/notes/vcr-ci-mode-99dbd2940fff8d7a.yaml, tests/conftest.py
Lets the VCR 3rd party API proxy run in "CI mode", which will return a 404 for cassette files that are not found in the designated vcr cassette directory. This will ensure that, if enabled for CI for a given repository, that all cassettes are generated locally, and there are no unintended side effects from missing cassettes.
This flag defaults to `false`. I've also separated it from the `--snapshot-ci-mode` flag, but we could easily consolidate if we wanted with backwards compatibility. Just didn't want to make too many code changes unrelated to the vcr aspect of the testagent.
=> feat(vcr): add ability to run in ci mode

ddapm_test_agent/agent.py, releasenotes/notes/add-errors-intake-proxy-endpoint-7e0f31d72a130f1a.yaml, tests/test_agent.py
Crashtracking wants to send crash reports to errors intake through the agent proxy. We should be able to test this behavior in unit tests in each of the runtime tracers
=> [crashtracking] Add errorsintake proxy endpoint
